print('Happy birthday anna')
print('One humble request anna when your free read it freely.Stay blessed anna always')
print('God will bless you always anna')
print('A Generous heart will quickly become a precious heart')
print('You are really generous in sharing your knowledge anna')
print('Really I am blessed to have you as my brother anna')
print('I did an unforgavable mistake that I was jealous of your mark I did not do knowlingly anna even though you wished me on my birthday after 4 years anna.At present,I am not like that anna,why I did that I do not know anna.I feel guilty really I am sorry anna.If normal person,they will not do anna because you have a generous heart anna ')
print('Everyone will forget but you did not do that ,really gifted to have you as my brother anna')
print('You are the great person I met ever anna ')
print('I suffered a lot because I do not know anything about computer.Anyway I learnt it for you anna. I thought asking but it will not be surprise for you anna.Because you surprised me twice for my birthday anna ')
print('Thank you a lot for everything anna')
print('You teached me as teacher, guided me as guide ,made happy by being as friend and brother')
print('You downloaded telegram for me,really great anna')
print('I do not know that you like it or not anna')
print('I did this for my sweet brother')
print('Be happy always anna')
print('You are a very good charactered person anna')
print('Even though I teased you or irritated you,you did not get angry with me anna')
print('You are very talented person anna and humble person anna')
print('1st a fall I do not like computer subject because of you only anna I liked computer subject anna.Because you only said what is computer.It is an intresting subject anna.')
print('Its rare to see like you person anna')
print('One kind request anna always or in any situation you want to be brother forever for your sister U.S.Devayosha anna')
print('Everything made me to wonder anna.Really very infrequent to see you anna')
print('You should not worry in your life for anything anna')
print('God will show the right path anna')
print('Never feel for past anna')
print('Always success will be with you forever anna')
print('Concentrate on your studies and reach your success anna')
print('Computer is a mysterious subject more than that your character is a mystery anna')
print('I want learn more from you anna')
print('You like to make everyone happy around you anna its a wonderful thing anna')
print('The time what I spent with you is a precious thing in the world anna')
print('You are a great artist anna')
print('Thank you for drawing my photo anna.I liked it a lot anna')
print('The days with you was really fun anna')
print('No one in the universe will not put this much effort anna.You are really really really  great anna')
print('Today is your day anna enjoy your day anna')
print('When there is faith and victory in the mind,success can be gained anna.If the thoughts are weak,there is defeat.Its a fact anna')
print('There is no defeat for you anna because your mind is full of faith and positiveness anna')
print('Always be ourselves anna do not ever try to change you character anna')
print('Be cool under every condition anna')
print('Faith in God means no fear anna')
print ('God is the only healer for all your problems')
print('Always do not forget anna you are very special anna.No one in the world cannot replace anna')
print('Never ever lose your hope in any situation anna.This is my humble request anna')
print('Do not waste time anna.You know that its a precious one anna')
print('Your character is like elixir anna')
print('When you try your best and your best is not good enough,leave it in the hands of God anna')
print('I do not know that you like me or not that does not matter but I like you so much anna.Because your my anna always in any situation I will never forget you anna.I will give more importance to the number 1 anna you are my only one anna so more importance will be given to you anna')
print('Once again a very very very happy happy happy birthday anna.If you like it I am happy anna if you do not like it also no problem anna.Be happy forever anna')
print('This a very very very small gift and surprise for you anna by your sweet sister U.S.Devayosha')